### ISSUE TITLE
Regarding PID

### ISSUE THREAD

**Issue by yuzukin** [aixxe/osu-relax#2]
Hi,
I've been wondering if there is a specific reason why you use CreateToolhelp32Snapshot to get the PID?
So far I always used the following but now I wonder if your way offers something I am not aware of?

`HWND winhnd = FindWindow(nullptr, "target process");

    DWORD pid;
    GetWindowThreadProcessId(winhnd, &pid);

    return pid;`

**Comment by aixxe** [comment]
The beta and cutting edge channels have different window titles last time I checked - also the window title would be different if playing a map. I just thought it would be easier to look for osu!.exe since it doesn't change even if the release channel is different.

**Comment by yuzukin** [comment]
Makes sense. I haven't dealt with anything that wildly changes the window title so snapshot seemed like overkill. Sorry for the bother.
Cheers
